CREATE TABLE PATIENTS (
    PATIENT_ID VARCHAR2(255) PRIMARY KEY,
    FIRST_NAME VARCHAR2(255),
    LAST_NAME VARCHAR2(255),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(20),
    ADDRESS_STREET VARCHAR2(255),
    ADDRESS_CITY VARCHAR2(255),
    ADDRESS_STATE VARCHAR2(255),
    ADDRESS_ZIP VARCHAR2(20),
    HL7_MESSAGE_TYPE VARCHAR2(255),
    RECEIVED_DATE DATE
);